name: GitHub Project Automation+
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, assigned, closed]

jobs:
  automate-project:
    runs-on: ubuntu-latest
    steps:
      - name: Automatizar Projeto no GitHub
        uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: ProvaConceito
          repo-token: ${{ secrets.GITHUB_TOKEN }}

